version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"sam-tutorial\""
image_repositories = []
confirm_changeset = true
